--; ==================================================
--; Lua Weather Six Hour Forecast
--; ==================================================

function updateSixHour()
	SKIN:Bang('!UpdateMeasure MeasureSixHourForecast')

	SKIN:Bang('!Log "Retrieving Forecast..."')
	SKIN:Bang('!HideMeter MeterIconHour1')
	SKIN:Bang('!HideMeter MeterIconHour2')
	SKIN:Bang('!HideMeter MeterIconHour3')
	SKIN:Bang('!HideMeter MeterIconHour4')
	SKIN:Bang('!HideMeter MeterIconHour5')
	SKIN:Bang('!HideMeter MeterIconHour6')
	SKIN:Bang('!HideMeter MeterPrecipitationHour1Image')
	SKIN:Bang('!HideMeter MeterPrecipitationHour2Image')
	SKIN:Bang('!HideMeter MeterPrecipitationHour3Image')
	SKIN:Bang('!HideMeter MeterPrecipitationHour4Image')
	SKIN:Bang('!HideMeter MeterPrecipitationHour5Image')
	SKIN:Bang('!HideMeter MeterPrecipitationHour6Image')
	SKIN:Bang('!HideMeter MeterWindHour1Image')
	SKIN:Bang('!HideMeter MeterWindHour2Image')
	SKIN:Bang('!HideMeter MeterWindHour3Image')
	SKIN:Bang('!HideMeter MeterWindHour4Image')
	SKIN:Bang('!HideMeter MeterWindHour5Image')
	SKIN:Bang('!HideMeter MeterWindHour6Image')
	
	SKIN:Bang('!HideMeter MeterTemperatureHour1')
	SKIN:Bang('!HideMeter MeterTemperatureHour2')
	SKIN:Bang('!HideMeter MeterTemperatureHour3')
	SKIN:Bang('!HideMeter MeterTemperatureHour4')
	SKIN:Bang('!HideMeter MeterTemperatureHour5')
	SKIN:Bang('!HideMeter MeterTemperatureHour6')
	SKIN:Bang('!HideMeter MeterValidTimeHour1')
	SKIN:Bang('!HideMeter MeterValidTimeHour2')
	SKIN:Bang('!HideMeter MeterValidTimeHour3')
	SKIN:Bang('!HideMeter MeterValidTimeHour4')
	SKIN:Bang('!HideMeter MeterValidTimeHour5')
	SKIN:Bang('!HideMeter MeterValidTimeHour6')
	SKIN:Bang('!HideMeter MeterConditionHour1')
	SKIN:Bang('!HideMeter MeterConditionHour2')
	SKIN:Bang('!HideMeter MeterConditionHour3')
	SKIN:Bang('!HideMeter MeterConditionHour4')
	SKIN:Bang('!HideMeter MeterConditionHour5')
	SKIN:Bang('!HideMeter MeterConditionHour6')
	SKIN:Bang('!HideMeter MeterPrecipitationHour1')
	SKIN:Bang('!HideMeter MeterPrecipitationHour2')
	SKIN:Bang('!HideMeter MeterPrecipitationHour3')
	SKIN:Bang('!HideMeter MeterPrecipitationHour4')
	SKIN:Bang('!HideMeter MeterPrecipitationHour5')
	SKIN:Bang('!HideMeter MeterPrecipitationHour6')
	SKIN:Bang('!HideMeter MeterWindCardinalSpeedHour1')
	SKIN:Bang('!HideMeter MeterWindCardinalSpeedHour2')
	SKIN:Bang('!HideMeter MeterWindCardinalSpeedHour3')
	SKIN:Bang('!HideMeter MeterWindCardinalSpeedHour4')
	SKIN:Bang('!HideMeter MeterWindCardinalSpeedHour5')
	SKIN:Bang('!HideMeter MeterWindCardinalSpeedHour6')

	SKIN:Bang('!DisableMeasure MeasureIconHour1')
	SKIN:Bang('!DisableMeasure MeasureIconHour2')
	SKIN:Bang('!DisableMeasure MeasureIconHour3')
	SKIN:Bang('!DisableMeasure MeasureIconHour4')
	SKIN:Bang('!DisableMeasure MeasureIconHour5')
	SKIN:Bang('!DisableMeasure MeasureIconHour6')
	SKIN:Bang('!DisableMeasure MeasurePrecipitationHour1')
	SKIN:Bang('!DisableMeasure MeasurePrecipitationHour2')
	SKIN:Bang('!DisableMeasure MeasurePrecipitationHour3')
	SKIN:Bang('!DisableMeasure MeasurePrecipitationHour4')
	SKIN:Bang('!DisableMeasure MeasurePrecipitationHour5')
	SKIN:Bang('!DisableMeasure MeasurePrecipitationHour6')
	SKIN:Bang('!DisableMeasure MeasureTempHour1')
	SKIN:Bang('!DisableMeasure MeasureTempFHour1')
	SKIN:Bang('!DisableMeasure MeasureTempCHour1')
	SKIN:Bang('!DisableMeasure MeasureTempHour2')
	SKIN:Bang('!DisableMeasure MeasureTempFHour2')
	SKIN:Bang('!DisableMeasure MeasureTempCHour2')
	SKIN:Bang('!DisableMeasure MeasureTempHour3')
	SKIN:Bang('!DisableMeasure MeasureTempFHour3')
	SKIN:Bang('!DisableMeasure MeasureTempCHour3')
	SKIN:Bang('!DisableMeasure MeasureTempHour4')
	SKIN:Bang('!DisableMeasure MeasureTempFHour4')
	SKIN:Bang('!DisableMeasure MeasureTempCHour4')
	SKIN:Bang('!DisableMeasure MeasureTempHour5')
	SKIN:Bang('!DisableMeasure MeasureTempFHour5')
	SKIN:Bang('!DisableMeasure MeasureTempCHour5')
	SKIN:Bang('!DisableMeasure MeasureTempHour6')
	SKIN:Bang('!DisableMeasure MeasureTempFHour6')
	SKIN:Bang('!DisableMeasure MeasureTempCHour6')
	SKIN:Bang('!DisableMeasure MeasureValidTime24HHour1')
	SKIN:Bang('!DisableMeasure MeasureValidTime12HHour1')
	SKIN:Bang('!DisableMeasure MeasureValidTime24HHour2')
	SKIN:Bang('!DisableMeasure MeasureValidTime12HHour2')
	SKIN:Bang('!DisableMeasure MeasureValidTime24HHour3')
	SKIN:Bang('!DisableMeasure MeasureValidTime12HHour3')
	SKIN:Bang('!DisableMeasure MeasureValidTime24HHour4')
	SKIN:Bang('!DisableMeasure MeasureValidTime12HHour4')
	SKIN:Bang('!DisableMeasure MeasureValidTime24HHour5')
	SKIN:Bang('!DisableMeasure MeasureValidTime12HHour5')
	SKIN:Bang('!DisableMeasure MeasureValidTime24HHour6')
	SKIN:Bang('!DisableMeasure MeasureValidTime12HHour6')
	SKIN:Bang('!DisableMeasure MeasureWindCardinalHour1')
	SKIN:Bang('!DisableMeasure MeasureWindCardinalHour2')
	SKIN:Bang('!DisableMeasure MeasureWindCardinalHour3')
	SKIN:Bang('!DisableMeasure MeasureWindCardinalHour4')
	SKIN:Bang('!DisableMeasure MeasureWindCardinalHour5')
	SKIN:Bang('!DisableMeasure MeasureWindCardinalHour6')
	SKIN:Bang('!DisableMeasure MeasureWindSpeedHour1')
	SKIN:Bang('!DisableMeasure MeasureWindSpeedMphHour1')
	SKIN:Bang('!DisableMeasure MeasureWindSpeedKmhHour1')
	SKIN:Bang('!DisableMeasure MeasureWindSpeedHour2')
	SKIN:Bang('!DisableMeasure MeasureWindSpeedMphHour2')
	SKIN:Bang('!DisableMeasure MeasureWindSpeedKmhHour2')
	SKIN:Bang('!DisableMeasure MeasureWindSpeedHour3')
	SKIN:Bang('!DisableMeasure MeasureWindSpeedMphHour3')
	SKIN:Bang('!DisableMeasure MeasureWindSpeedKmhHour3')
	SKIN:Bang('!DisableMeasure MeasureWindSpeedHour4')
	SKIN:Bang('!DisableMeasure MeasureWindSpeedMphHour4')
	SKIN:Bang('!DisableMeasure MeasureWindSpeedKmhHour4')
	SKIN:Bang('!DisableMeasure MeasureWindSpeedHour5')
	SKIN:Bang('!DisableMeasure MeasureWindSpeedMphHour5')
	SKIN:Bang('!DisableMeasure MeasureWindSpeedKmhHour5')
	SKIN:Bang('!DisableMeasure MeasureWindSpeedHour6')
	SKIN:Bang('!DisableMeasure MeasureWindSpeedMphHour6')
	SKIN:Bang('!DisableMeasure MeasureWindSpeedKmhHour6')
	SKIN:Bang('!DisableMeasure MeasureConditionHour1')
	SKIN:Bang('!DisableMeasure MeasureConditionHour2')
	SKIN:Bang('!DisableMeasure MeasureConditionHour3')
	SKIN:Bang('!DisableMeasure MeasureConditionHour4')
	SKIN:Bang('!DisableMeasure MeasureConditionHour5')
	SKIN:Bang('!DisableMeasure MeasureConditionHour6')
	SKIN:Bang('!DisableMeasure MeasureWindMphSixHour')
	SKIN:Bang('!DisableMeasure MeasureWindKmhSixHour')
	
end

function finishSixHour()
	SKIN:Bang('!Log "Retrieved Forecast"')
	SKIN:Bang('!ShowMeter MeterIconHour1')
	SKIN:Bang('!ShowMeter MeterIconHour2')
	SKIN:Bang('!ShowMeter MeterIconHour3')
	SKIN:Bang('!ShowMeter MeterIconHour4')
	SKIN:Bang('!ShowMeter MeterIconHour5')
	SKIN:Bang('!ShowMeter MeterIconHour6')
	SKIN:Bang('!ShowMeter MeterPrecipitationHour1Image')
	SKIN:Bang('!ShowMeter MeterPrecipitationHour2Image')
	SKIN:Bang('!ShowMeter MeterPrecipitationHour3Image')
	SKIN:Bang('!ShowMeter MeterPrecipitationHour4Image')
	SKIN:Bang('!ShowMeter MeterPrecipitationHour5Image')
	SKIN:Bang('!ShowMeter MeterPrecipitationHour6Image')
	SKIN:Bang('!ShowMeter MeterWindHour1Image')
	SKIN:Bang('!ShowMeter MeterWindHour2Image')
	SKIN:Bang('!ShowMeter MeterWindHour3Image')
	SKIN:Bang('!ShowMeter MeterWindHour4Image')
	SKIN:Bang('!ShowMeter MeterWindHour5Image')
	SKIN:Bang('!ShowMeter MeterWindHour6Image')
	
	SKIN:Bang('!ShowMeter MeterTemperatureHour1')
	SKIN:Bang('!ShowMeter MeterTemperatureHour2')
	SKIN:Bang('!ShowMeter MeterTemperatureHour3')
	SKIN:Bang('!ShowMeter MeterTemperatureHour4')
	SKIN:Bang('!ShowMeter MeterTemperatureHour5')
	SKIN:Bang('!ShowMeter MeterTemperatureHour6')
	SKIN:Bang('!ShowMeter MeterValidTimeHour1')
	SKIN:Bang('!ShowMeter MeterValidTimeHour2')
	SKIN:Bang('!ShowMeter MeterValidTimeHour3')
	SKIN:Bang('!ShowMeter MeterValidTimeHour4')
	SKIN:Bang('!ShowMeter MeterValidTimeHour5')
	SKIN:Bang('!ShowMeter MeterValidTimeHour6')
	SKIN:Bang('!ShowMeter MeterConditionHour1')
	SKIN:Bang('!ShowMeter MeterConditionHour2')
	SKIN:Bang('!ShowMeter MeterConditionHour3')
	SKIN:Bang('!ShowMeter MeterConditionHour4')
	SKIN:Bang('!ShowMeter MeterConditionHour5')
	SKIN:Bang('!ShowMeter MeterConditionHour6')
	SKIN:Bang('!ShowMeter MeterPrecipitationHour1')
	SKIN:Bang('!ShowMeter MeterPrecipitationHour2')
	SKIN:Bang('!ShowMeter MeterPrecipitationHour3')
	SKIN:Bang('!ShowMeter MeterPrecipitationHour4')
	SKIN:Bang('!ShowMeter MeterPrecipitationHour5')
	SKIN:Bang('!ShowMeter MeterPrecipitationHour6')
	SKIN:Bang('!ShowMeter MeterWindCardinalSpeedHour1')
	SKIN:Bang('!ShowMeter MeterWindCardinalSpeedHour2')
	SKIN:Bang('!ShowMeter MeterWindCardinalSpeedHour3')
	SKIN:Bang('!ShowMeter MeterWindCardinalSpeedHour4')
	SKIN:Bang('!ShowMeter MeterWindCardinalSpeedHour5')
	SKIN:Bang('!ShowMeter MeterWindCardinalSpeedHour6')

	SKIN:Bang('!EnableMeasure MeasureIconHour1')
	SKIN:Bang('!EnableMeasure MeasureIconHour2')
	SKIN:Bang('!EnableMeasure MeasureIconHour3')
	SKIN:Bang('!EnableMeasure MeasureIconHour4')
	SKIN:Bang('!EnableMeasure MeasureIconHour5')
	SKIN:Bang('!EnableMeasure MeasureIconHour6')
	SKIN:Bang('!EnableMeasure MeasurePrecipitationHour1')
	SKIN:Bang('!EnableMeasure MeasurePrecipitationHour2')
	SKIN:Bang('!EnableMeasure MeasurePrecipitationHour3')
	SKIN:Bang('!EnableMeasure MeasurePrecipitationHour4')
	SKIN:Bang('!EnableMeasure MeasurePrecipitationHour5')
	SKIN:Bang('!EnableMeasure MeasurePrecipitationHour6')
	SKIN:Bang('!EnableMeasure MeasureTempHour1')
	SKIN:Bang('!EnableMeasure MeasureTempFHour1')
	SKIN:Bang('!EnableMeasure MeasureTempCHour1')
	SKIN:Bang('!EnableMeasure MeasureTempHour2')
	SKIN:Bang('!EnableMeasure MeasureTempFHour2')
	SKIN:Bang('!EnableMeasure MeasureTempCHour2')
	SKIN:Bang('!EnableMeasure MeasureTempHour3')
	SKIN:Bang('!EnableMeasure MeasureTempFHour3')
	SKIN:Bang('!EnableMeasure MeasureTempCHour3')
	SKIN:Bang('!EnableMeasure MeasureTempHour4')
	SKIN:Bang('!EnableMeasure MeasureTempFHour4')
	SKIN:Bang('!EnableMeasure MeasureTempCHour4')
	SKIN:Bang('!EnableMeasure MeasureTempHour5')
	SKIN:Bang('!EnableMeasure MeasureTempFHour5')
	SKIN:Bang('!EnableMeasure MeasureTempCHour5')
	SKIN:Bang('!EnableMeasure MeasureTempHour6')
	SKIN:Bang('!EnableMeasure MeasureTempFHour6')
	SKIN:Bang('!EnableMeasure MeasureTempCHour6')
	SKIN:Bang('!EnableMeasure MeasureValidTime24HHour1')
	SKIN:Bang('!EnableMeasure MeasureValidTime12HHour1')
	SKIN:Bang('!EnableMeasure MeasureValidTime24HHour2')
	SKIN:Bang('!EnableMeasure MeasureValidTime12HHour2')
	SKIN:Bang('!EnableMeasure MeasureValidTime24HHour3')
	SKIN:Bang('!EnableMeasure MeasureValidTime12HHour3')
	SKIN:Bang('!EnableMeasure MeasureValidTime24HHour4')
	SKIN:Bang('!EnableMeasure MeasureValidTime12HHour4')
	SKIN:Bang('!EnableMeasure MeasureValidTime24HHour5')
	SKIN:Bang('!EnableMeasure MeasureValidTime12HHour5')
	SKIN:Bang('!EnableMeasure MeasureValidTime24HHour6')
	SKIN:Bang('!EnableMeasure MeasureValidTime12HHour6')
	SKIN:Bang('!EnableMeasure MeasureWindCardinalHour1')
	SKIN:Bang('!EnableMeasure MeasureWindCardinalHour2')
	SKIN:Bang('!EnableMeasure MeasureWindCardinalHour3')
	SKIN:Bang('!EnableMeasure MeasureWindCardinalHour4')
	SKIN:Bang('!EnableMeasure MeasureWindCardinalHour5')
	SKIN:Bang('!EnableMeasure MeasureWindCardinalHour6')
	SKIN:Bang('!EnableMeasure MeasureWindSpeedHour1')
	SKIN:Bang('!EnableMeasure MeasureWindSpeedMphHour1')
	SKIN:Bang('!EnableMeasure MeasureWindSpeedKmhHour1')
	SKIN:Bang('!EnableMeasure MeasureWindSpeedHour2')
	SKIN:Bang('!EnableMeasure MeasureWindSpeedMphHour2')
	SKIN:Bang('!EnableMeasure MeasureWindSpeedKmhHour2')
	SKIN:Bang('!EnableMeasure MeasureWindSpeedHour3')
	SKIN:Bang('!EnableMeasure MeasureWindSpeedMphHour3')
	SKIN:Bang('!EnableMeasure MeasureWindSpeedKmhHour3')
	SKIN:Bang('!EnableMeasure MeasureWindSpeedHour4')
	SKIN:Bang('!EnableMeasure MeasureWindSpeedMphHour4')
	SKIN:Bang('!EnableMeasure MeasureWindSpeedKmhHour4')
	SKIN:Bang('!EnableMeasure MeasureWindSpeedHour5')
	SKIN:Bang('!EnableMeasure MeasureWindSpeedMphHour5')
	SKIN:Bang('!EnableMeasure MeasureWindSpeedKmhHour5')
	SKIN:Bang('!EnableMeasure MeasureWindSpeedHour6')
	SKIN:Bang('!EnableMeasure MeasureWindSpeedMphHour6')
	SKIN:Bang('!EnableMeasure MeasureWindSpeedKmhHour6')
	SKIN:Bang('!EnableMeasure MeasureConditionHour1')
	SKIN:Bang('!EnableMeasure MeasureConditionHour2')
	SKIN:Bang('!EnableMeasure MeasureConditionHour3')
	SKIN:Bang('!EnableMeasure MeasureConditionHour4')
	SKIN:Bang('!EnableMeasure MeasureConditionHour5')
	SKIN:Bang('!EnableMeasure MeasureConditionHour6')
	SKIN:Bang('!EnableMeasure MeasureWindMphSixHour')
	SKIN:Bang('!EnableMeasure MeasureWindKmhSixHour')
	
	SKIN:Bang('!UpdateMeter *')

end

sixhourTime = {
	["12 Hours"] = {
		measValid = "MeasureValidTime12H",
		coreSHTime = "12H",
		varSHToggle = "0"
	},
	["24 Hours"] = {
		measValid = "MeasureValidTime24H",
		coreSHTime = "24H",
		varSHToggle = "1"
	}
}

function setSixHour(selectedTime)
	SKIN:Bang('!SetVariable SixHourTime "' .. sixhourTime[selectedTime]['coreSHTime'] .. '" "#CoreFilePath#"')
	SKIN:Bang('!WriteKeyValue Variables SixHourToggle "' .. sixhourTime[selectedTime]['varSHToggle'] .. '" "#@#Variables.inc"')

	SKIN:Bang('!SetOption MeterValidTimeHour1 MeasureName "' .. sixhourTime[selectedTime]['measValid'] .. 'Hour1"')
	SKIN:Bang('!SetOption MeterValidTimeHour2 MeasureName "' .. sixhourTime[selectedTime]['measValid'] .. 'Hour2"')
	SKIN:Bang('!SetOption MeterValidTimeHour3 MeasureName "' .. sixhourTime[selectedTime]['measValid'] .. 'Hour3"')
	SKIN:Bang('!SetOption MeterValidTimeHour4 MeasureName "' .. sixhourTime[selectedTime]['measValid'] .. 'Hour4"')
	SKIN:Bang('!SetOption MeterValidTimeHour5 MeasureName "' .. sixhourTime[selectedTime]['measValid'] .. 'Hour5"')
	SKIN:Bang('!SetOption MeterValidTimeHour6 MeasureName "' .. sixhourTime[selectedTime]['measValid'] .. 'Hour6"')

	SKIN:Bang('!UpdateMeterGroup WeatherSixHourMeter')
	
end
