--; ==================================================
--; Lua Weather One Day Forecast
--; ==================================================

function updateOneDay()
	SKIN:Bang('!UpdateMeasure MeasureOneDayForecast')

	SKIN:Bang('!Log "Retrieving Daily Forecast..."')
	SKIN:Bang('!HideMeter MeterTodayIcon')
	SKIN:Bang('!HideMeter MeterTodayPrecipImage')
	SKIN:Bang('!HideMeter MeterTodayWindImage')
	SKIN:Bang('!HideMeter MeterTodayHumidImage')
	SKIN:Bang('!HideMeter MeterTodayUVImage')
	SKIN:Bang('!HideMeter MeterSunriseImage')
	SKIN:Bang('!HideMeter MeterSunsetImage')
	SKIN:Bang('!HideMeter MeterTonightIcon')
	SKIN:Bang('!HideMeter MeterTonightPrecipImage')
	SKIN:Bang('!HideMeter MeterTonightWindImage')
	SKIN:Bang('!HideMeter MeterTonightHumidImage')
	SKIN:Bang('!HideMeter MeterTonightUVImage')
	SKIN:Bang('!HideMeter MeterMoonriseImage')
	SKIN:Bang('!HideMeter MeterMoonsetImage')
	
	SKIN:Bang('!HideMeter MeterTodayText')
	SKIN:Bang('!HideMeter MeterTodayTemperature')
	SKIN:Bang('!HideMeter MeterTodayPrecipitation')
	SKIN:Bang('!HideMeter MeterTodayWindCardinalSpeed')
	SKIN:Bang('!HideMeter MeterTodayHumidityText')
	SKIN:Bang('!HideMeter MeterTodayHumidity')
	SKIN:Bang('!HideMeter MeterTodayUVIndexText')
	SKIN:Bang('!HideMeter MeterTodayUVIndex')
	SKIN:Bang('!HideMeter MeterSunriseText')
	SKIN:Bang('!HideMeter MeterSunrise')
	SKIN:Bang('!HideMeter MeterSunsetText')
	SKIN:Bang('!HideMeter MeterSunset')
	SKIN:Bang('!HideMeter MeterTonightText')
	SKIN:Bang('!HideMeter MeterTonightTemperature')
	SKIN:Bang('!HideMeter MeterTonightPrecipitation')
	SKIN:Bang('!HideMeter MeterTonightWindCardinalSpeed')
	SKIN:Bang('!HideMeter MeterTonightHumidityText')
	SKIN:Bang('!HideMeter MeterTonightHumidity')
	SKIN:Bang('!HideMeter MeterTonightUVIndexText')
	SKIN:Bang('!HideMeter MeterTonightUVIndex')
	SKIN:Bang('!HideMeter MeterMoonriseText')
	SKIN:Bang('!HideMeter MeterMoonrise')
	SKIN:Bang('!HideMeter MeterMoonsetText')
	SKIN:Bang('!HideMeter MeterMoonset')

	SKIN:Bang('!DisableMeasure MeasureOneDayUnits')
	SKIN:Bang('!DisableMeasure MeasureDayOfWeek')
	SKIN:Bang('!DisableMeasure MeasureOneDayMoonrise24H')
	SKIN:Bang('!DisableMeasure MeasureOneDayMoonset24H')
	SKIN:Bang('!DisableMeasure MeasureTwoDayMoonrise24H')
	SKIN:Bang('!DisableMeasure MeasureTwoDayMoonset24H')
	SKIN:Bang('!DisableMeasure MeasureOneDayMoonrise12H')
	SKIN:Bang('!DisableMeasure MeasureOneDayMoonset12H')
	SKIN:Bang('!DisableMeasure MeasureOneDaySunrise24H')
	SKIN:Bang('!DisableMeasure MeasureOneDaySunset24H')
	SKIN:Bang('!DisableMeasure MeasureTwoDaySunrise24H')
	SKIN:Bang('!DisableMeasure MeasureTwoDaySunset24H')
	SKIN:Bang('!DisableMeasure MeasureOneDaySunrise12H')
	SKIN:Bang('!DisableMeasure MeasureOneDaySunset12H')
	SKIN:Bang('!DisableMeasure MeasureToday')
	SKIN:Bang('!DisableMeasure MeasureTonight')
	SKIN:Bang('!DisableMeasure MeasureTodayIcon')
	SKIN:Bang('!DisableMeasure MeasureTonightIcon')
	SKIN:Bang('!DisableMeasure MeasureNextDayIcon')
	SKIN:Bang('!DisableMeasure MeasureTodayPrecipitation')
	SKIN:Bang('!DisableMeasure MeasureTonightPrecipitation')
	SKIN:Bang('!DisableMeasure MeasureNextDayPrecipitation')
	SKIN:Bang('!DisableMeasure MeasureTodayHumidity')
	SKIN:Bang('!DisableMeasure MeasureTonightHumidity')
	SKIN:Bang('!DisableMeasure MeasureNextDayHumidity')
	SKIN:Bang('!DisableMeasure MeasureTodayTemperature')
	SKIN:Bang('!DisableMeasure MeasureTodayTemperatureF')
	SKIN:Bang('!DisableMeasure MeasureTodayTemperatureC')
	SKIN:Bang('!DisableMeasure MeasureTonightTemperature')
	SKIN:Bang('!DisableMeasure MeasureTonightTemperatureF')
	SKIN:Bang('!DisableMeasure MeasureTonightTemperatureC')
	SKIN:Bang('!DisableMeasure MeasureNextDayTemperature')
	SKIN:Bang('!DisableMeasure MeasureNextDayTemperatureF')
	SKIN:Bang('!DisableMeasure MeasureNextDayTemperatureC')
	SKIN:Bang('!DisableMeasure MeasureTodayUVIndex')
	SKIN:Bang('!DisableMeasure MeasureTonightUVIndex')
	SKIN:Bang('!DisableMeasure MeasureNextDayUVIndex')
	SKIN:Bang('!DisableMeasure MeasureTodayWindCardinal')
	SKIN:Bang('!DisableMeasure MeasureTonightWindCardinal')
	SKIN:Bang('!DisableMeasure MeasureNextDayWindCardinal')
	SKIN:Bang('!DisableMeasure MeasureTodayWindSpeed')
	SKIN:Bang('!DisableMeasure MeasureTodayWindSpeedMph')
	SKIN:Bang('!DisableMeasure MeasureTodayWindSpeedKmh')
	SKIN:Bang('!DisableMeasure MeasureTonightWindSpeed')
	SKIN:Bang('!DisableMeasure MeasureTonightWindSpeedMph')
	SKIN:Bang('!DisableMeasure MeasureTonightWindSpeedKmh')
	SKIN:Bang('!DisableMeasure MeasureNextDayWindSpeed')
	SKIN:Bang('!DisableMeasure MeasureNextDayWindSpeedMph')
	SKIN:Bang('!DisableMeasure MeasureNextDayWindSpeedKmh')
	SKIN:Bang('!DisableMeasure MeasureTodayCondition')
	SKIN:Bang('!DisableMeasure MeasureTonightCondition')
	SKIN:Bang('!DisableMeasure MeasureNextDayCondition')
	SKIN:Bang('!DisableMeasure MeasureOneDayWindMph')
	SKIN:Bang('!DisableMeasure MeasureOneDayWindKmh')
	SKIN:Bang('!DisableMeasure MeasureOneDayUVOf')
	SKIN:Bang('!DisableMeasure MeasureOneDayUVExtreme')
	SKIN:Bang('!DisableMeasure MeasureOneDayHumidityText')
	SKIN:Bang('!DisableMeasure MeasureOneDayUVIndexText')
	SKIN:Bang('!DisableMeasure MeasureOneDaySunriseText')
	SKIN:Bang('!DisableMeasure MeasureOneDaySunsetText')
	SKIN:Bang('!DisableMeasure MeasureOneDayMoonriseText')
	SKIN:Bang('!DisableMeasure MeasureOneDayMoonsetText')
	
end

function finishOneDay()
	SKIN:Bang('!Log "Retrieved Daily Forecast"')
	SKIN:Bang('!ShowMeter MeterTodayIcon')
	SKIN:Bang('!ShowMeter MeterTodayPrecipImage')
	SKIN:Bang('!ShowMeter MeterTodayWindImage')
	SKIN:Bang('!ShowMeter MeterTodayHumidImage')
	SKIN:Bang('!ShowMeter MeterTodayUVImage')
	SKIN:Bang('!ShowMeter MeterSunriseImage')
	SKIN:Bang('!ShowMeter MeterSunsetImage')
	SKIN:Bang('!ShowMeter MeterTonightIcon')
	SKIN:Bang('!ShowMeter MeterTonightPrecipImage')
	SKIN:Bang('!ShowMeter MeterTonightWindImage')
	SKIN:Bang('!ShowMeter MeterTonightHumidImage')
	SKIN:Bang('!ShowMeter MeterTonightUVImage')
	SKIN:Bang('!ShowMeter MeterMoonriseImage')
	SKIN:Bang('!ShowMeter MeterMoonsetImage')
	
	SKIN:Bang('!ShowMeter MeterTodayText')
	SKIN:Bang('!ShowMeter MeterTodayTemperature')
	SKIN:Bang('!ShowMeter MeterTodayPrecipitation')
	SKIN:Bang('!ShowMeter MeterTodayWindCardinalSpeed')
	SKIN:Bang('!ShowMeter MeterTodayHumidityText')
	SKIN:Bang('!ShowMeter MeterTodayHumidity')
	SKIN:Bang('!ShowMeter MeterTodayUVIndexText')
	SKIN:Bang('!ShowMeter MeterTodayUVIndex')
	SKIN:Bang('!ShowMeter MeterSunriseText')
	SKIN:Bang('!ShowMeter MeterSunrise')
	SKIN:Bang('!ShowMeter MeterSunsetText')
	SKIN:Bang('!ShowMeter MeterSunset')
	SKIN:Bang('!ShowMeter MeterTonightText')
	SKIN:Bang('!ShowMeter MeterTonightTemperature')
	SKIN:Bang('!ShowMeter MeterTonightPrecipitation')
	SKIN:Bang('!ShowMeter MeterTonightWindCardinalSpeed')
	SKIN:Bang('!ShowMeter MeterTonightHumidityText')
	SKIN:Bang('!ShowMeter MeterTonightHumidity')
	SKIN:Bang('!ShowMeter MeterTonightUVIndexText')
	SKIN:Bang('!ShowMeter MeterTonightUVIndex')
	SKIN:Bang('!ShowMeter MeterMoonriseText')
	SKIN:Bang('!ShowMeter MeterMoonrise')
	SKIN:Bang('!ShowMeter MeterMoonsetText')
	SKIN:Bang('!ShowMeter MeterMoonset')
	
	SKIN:Bang('!EnableMeasure MeasureOneDayUnits')
	SKIN:Bang('!EnableMeasure MeasureDayOfWeek')
	SKIN:Bang('!EnableMeasure MeasureOneDayMoonrise24H')
	SKIN:Bang('!EnableMeasure MeasureOneDayMoonset24H')
	SKIN:Bang('!EnableMeasure MeasureTwoDayMoonrise24H')
	SKIN:Bang('!EnableMeasure MeasureTwoDayMoonset24H')
	SKIN:Bang('!EnableMeasure MeasureOneDayMoonrise12H')
	SKIN:Bang('!EnableMeasure MeasureOneDayMoonset12H')
	SKIN:Bang('!EnableMeasure MeasureOneDaySunrise24H')
	SKIN:Bang('!EnableMeasure MeasureOneDaySunset24H')
	SKIN:Bang('!EnableMeasure MeasureTwoDaySunrise24H')
	SKIN:Bang('!EnableMeasure MeasureTwoDaySunset24H')
	SKIN:Bang('!EnableMeasure MeasureOneDaySunrise12H')
	SKIN:Bang('!EnableMeasure MeasureOneDaySunset12H')
	SKIN:Bang('!EnableMeasure MeasureToday')
	SKIN:Bang('!EnableMeasure MeasureTonight')
	SKIN:Bang('!EnableMeasure MeasureTodayIcon')
	SKIN:Bang('!EnableMeasure MeasureTonightIcon')
	SKIN:Bang('!EnableMeasure MeasureNextDayIcon')
	SKIN:Bang('!EnableMeasure MeasureTodayPrecipitation')
	SKIN:Bang('!EnableMeasure MeasureTonightPrecipitation')
	SKIN:Bang('!EnableMeasure MeasureNextDayPrecipitation')
	SKIN:Bang('!EnableMeasure MeasureTodayHumidity')
	SKIN:Bang('!EnableMeasure MeasureTonightHumidity')
	SKIN:Bang('!EnableMeasure MeasureNextDayHumidity')
	SKIN:Bang('!EnableMeasure MeasureTodayTemperature')
	SKIN:Bang('!EnableMeasure MeasureTodayTemperatureF')
	SKIN:Bang('!EnableMeasure MeasureTodayTemperatureC')
	SKIN:Bang('!EnableMeasure MeasureTonightTemperature')
	SKIN:Bang('!EnableMeasure MeasureTonightTemperatureF')
	SKIN:Bang('!EnableMeasure MeasureTonightTemperatureC')
	SKIN:Bang('!EnableMeasure MeasureNextDayTemperature')
	SKIN:Bang('!EnableMeasure MeasureNextDayTemperatureF')
	SKIN:Bang('!EnableMeasure MeasureNextDayTemperatureC')
	SKIN:Bang('!EnableMeasure MeasureTodayUVIndex')
	SKIN:Bang('!EnableMeasure MeasureTonightUVIndex')
	SKIN:Bang('!EnableMeasure MeasureNextDayUVIndex')
	SKIN:Bang('!EnableMeasure MeasureTodayWindCardinal')
	SKIN:Bang('!EnableMeasure MeasureTonightWindCardinal')
	SKIN:Bang('!EnableMeasure MeasureNextDayWindCardinal')
	SKIN:Bang('!EnableMeasure MeasureTodayWindSpeed')
	SKIN:Bang('!EnableMeasure MeasureTodayWindSpeedMph')
	SKIN:Bang('!EnableMeasure MeasureTodayWindSpeedKmh')
	SKIN:Bang('!EnableMeasure MeasureTonightWindSpeed')
	SKIN:Bang('!EnableMeasure MeasureTonightWindSpeedMph')
	SKIN:Bang('!EnableMeasure MeasureTonightWindSpeedKmh')
	SKIN:Bang('!EnableMeasure MeasureNextDayWindSpeed')
	SKIN:Bang('!EnableMeasure MeasureNextDayWindSpeedMph')
	SKIN:Bang('!EnableMeasure MeasureNextDayWindSpeedKmh')
	SKIN:Bang('!EnableMeasure MeasureTodayCondition')
	SKIN:Bang('!EnableMeasure MeasureTonightCondition')
	SKIN:Bang('!EnableMeasure MeasureNextDayCondition')
	SKIN:Bang('!EnableMeasure MeasureOneDayWindMph')
	SKIN:Bang('!EnableMeasure MeasureOneDayWindKmh')
	SKIN:Bang('!EnableMeasure MeasureOneDayUVOf')
	SKIN:Bang('!EnableMeasure MeasureOneDayUVExtreme')
	SKIN:Bang('!EnableMeasure MeasureOneDayHumidityText')
	SKIN:Bang('!EnableMeasure MeasureOneDayUVIndexText')
	SKIN:Bang('!EnableMeasure MeasureOneDaySunriseText')
	SKIN:Bang('!EnableMeasure MeasureOneDaySunsetText')
	SKIN:Bang('!EnableMeasure MeasureOneDayMoonriseText')
	SKIN:Bang('!EnableMeasure MeasureOneDayMoonsetText')

	SKIN:Bang('!UpdateMeter *')

end

function scaleUpOneDay()
	SKIN:Bang('!WriteKeyValue Variables OneDayScale "(#OneDayScale#+#ScrollMouseIncrement#)" "#@#Variables.inc"')
	SKIN:Bang('!SetVariable OneDayScale "(#OneDayScale#+#ScrollMouseIncrement#)" "#CoreScaleFilePath#"')
	SKIN:Bang('!UpdateMeterGroup OneDayGroup')
	
end

function scaleDownOneDay()
	SKIN:Bang('!WriteKeyValue Variables OneDayScale "(#OneDayScale#-#ScrollMouseIncrement# < 0.5 ? 0.5 : #OneDayScale#-#ScrollMouseIncrement#)" "#@#Variables.inc"')
	SKIN:Bang('!SetVariable OneDayScale "(#OneDayScale#-#ScrollMouseIncrement# < 0.5 ? 0.5 : #OneDayScale#-#ScrollMouseIncrement#)" "#CoreScaleFilePath#"')
	SKIN:Bang('!UpdateMeterGroup OneDayGroup')

end

function matchTonight()
	SKIN:Bang('!SetOption MeterTodayIcon ImageName "[MeasureTonightIcon].png"')
	SKIN:Bang('!SetOption MeterTodayTemperature MeasureName "MeasureTonightTemperature#OneDayTemp#"')
	SKIN:Bang('!SetOption MeterTodayPrecipitation MeasureName "MeasureTonightPrecipitation"')
	SKIN:Bang('!SetOption MeterTodayWindCardinalSpeed MeasureName "MeasureTonightWindCardinal"')
	SKIN:Bang('!SetOption MeterTodayWindCardinalSpeed MeasureName2 "MeasureTonightWindSpeed#OneDayWind#"')
	SKIN:Bang('!SetOption MeterTodayHumidity MeasureName "MeasureTonightHumidity"')
	SKIN:Bang('!SetOption MeterTodayUVIndex MeasureName "MeasureTonightUVIndex"')
	SKIN:Bang('!SetOption MeterSunriseImage ImageName "Moonrise.png"')
	SKIN:Bang('!SetOption MeterSunriseText MeasureName "MeasureOneDayMoonriseText"')
	SKIN:Bang('!SetOption MeterSunrise MeasureName "MeasureOneDayMoonrise#OneDayTime#"')
	SKIN:Bang('!SetOption MeterSunsetImage ImageName "Moonset.png"')
	SKIN:Bang('!SetOption MeterSunsetText MeasureName "MeasureOneDayMoonsetText"')
	SKIN:Bang('!SetOption MeterSunset MeasureName "MeasureOneDayMoonset#OneDayTime#"')

	SKIN:Bang('!UpdateMeterGroup WeatherOneDayMeter')

end	

function matchTomorrow()
	SKIN:Bang('!SetOption MeterTonightIcon ImageName "[MeasureNextDayIcon].png"')
	SKIN:Bang('!SetOption MeterTonightTemperature MeasureName "MeasureNextDayTemperature#OneDayTemp#"')
	SKIN:Bang('!SetOption MeterTonightPrecipitation MeasureName "MeasureNextDayPrecipitation"')
	SKIN:Bang('!SetOption MeterTonightWindCardinalSpeed MeasureName "MeasureNextDayWindCardinal"')
	SKIN:Bang('!SetOption MeterTonightWindCardinalSpeed MeasureName2 "MeasureNextDayWindSpeed#OneDayWind#"')
	SKIN:Bang('!SetOption MeterTonightHumidity MeasureName "MeasureNextDayHumidity"')
	SKIN:Bang('!SetOption MeterTonightUVIndex MeasureName "MeasureNextDayUVIndex"')
	SKIN:Bang('!SetOption MeterMoonriseImage ImageName "Sunrise.png"')
	SKIN:Bang('!SetOption MeterMoonriseText MeasureName "MeasureOneDaySunriseText"')
	SKIN:Bang('!SetOption MeterMoonrise MeasureName "MeasureOneDaySunrise#OneDayTime#"')
	SKIN:Bang('!SetOption MeterMoonsetImage ImageName "Sunset.png"')
	SKIN:Bang('!SetOption MeterMoonsetText MeasureName "MeasureOneDaySunsetText"')
	SKIN:Bang('!SetOption MeterMoonset MeasureName "MeasureOneDaySunset#OneDayTime#"')

	SKIN:Bang('!UpdateMeterGroup WeatherOneDayMeter')
	
end	
