[Variables]

Page=Info
PageLine=80

TypeFace=Roboto
ColorText=White
ColorCode=255,255,255

LangName=English
LangCurrent=English (US)
TempUnit=Fahrenheit
WindUnit=Mph
WindUnitShort=Mph
VisibilityUnit=Mile
VisibilityUnitShort=Mi
PressureUnit=Inches
PressureUnitShort=In

; ====================================================================================================

CurrentTimeToggle=1
OneHourTimeToggle=0
FullHourTimeToggle=1
OneDayTimeToggle=1
OneDaySlimTimeToggle=1

CurrentTime=12H
OneHourTime=24H
FullHourTime=12H
OneDayTime=12H
OneDaySlimTime=12H

; ====================================================================================================

WeatherScale=1
ScrollMouseIncrement=0.1
