[Variables]

Page=Info
PageLine=80

LangCurrent=English (US)
TempUnit=Fahrenheit
WindUnit=Mph
VisibilityUnit=Mile
PressureUnit=Inches

; ====================================================================================================

CurrentToggle=1
CurrentSlimToggle=1
CurrentExtraSlimToggle=1
OneHourToggle=1
SixHourToggle=1
OneDayToggle=1
OneDaySlimToggle=1
SevenDayToggle=1

; ====================================================================================================

CurrentTemp=F
CurrentWind=Mph
CurrentVis=Mi
CurrentPress=In

CurrentSlimTemp=F
CurrentSlimWind=Mph
CurrentSlimVis=Mi

CurrentExtraSlimTemp=F

; ====================================================================================================

OneHourTemp=F
OneHourWind=Mph

SixHourTemp=F
SixHourWind=Mph

; ====================================================================================================

OneDayTemp=F
OneDayWind=Mph

OneDaySlimTemp=F
OneDaySlimWind=Mph

SevenDayTemp=F
SevenDayWind=Mph

; ====================================================================================================

CurrentTimeToggle=1
OneHourTimeToggle=0
SixHourTimeToggle=0
OneDayTimeToggle=0
OneDaySlimTimeToggle=0

CurrentTime=12H
OneHourTime=24H
SixHourTime=24H
OneDayTime=24H
OneDaySlimTime=24H

; ====================================================================================================

AQPrimaryColor=FFFF2480
AQNO2Color=00E838
AQO3Color=00E838
AQSO2Color=00E838
AQPM25Color=FFFF24
AQPM10Color=00E838
AQCOColor=00E838

AQPrimaryIndex=120
AQNO2Index=60
AQO3Index=60
AQSO2Index=60
AQPM25Index=120
AQPM10Index=60
AQCOIndex=60

; ====================================================================================================

CurrentScale=1
CurrentSlimScale=1
CurrentExtraSlimScale=0.9
OneHourScale=1
SixHourScale=1
OneDayScale=1
OneDaySlimScale=1
SevenDayScale=1
AirQualityScale=1
ScrollMouseIncrement=0.1
