[Variables]

CurrentToggle=1
CurrentSlimToggle=1
CurrentExtraSlimToggle=1
OneHourToggle=1
SixHourToggle=1
OneDayToggle=1
OneDaySlimToggle=1
SevenDayToggle=1

; ====================================================================================================

CurrentTemp=F
CurrentWind=Mph
CurrentVis=Mi
CurrentPress=Mb

CurrentSlimTemp=F
CurrentSlimWind=Mph
CurrentSlimVis=Mi

CurrentExtraSlimTemp=F

; ====================================================================================================

OneHourTemp=F
OneHourWind=Mph

SixHourTemp=F
SixHourWind=Mph

; ====================================================================================================

OneDayTemp=F
OneDayWind=Mph

OneDaySlimTemp=F
OneDaySlimWind=Mph

SevenDayTemp=F
SevenDayWind=Mph

; ====================================================================================================

CurrentTimeToggle=1
OneHourTimeToggle=1
SixHourTimeToggle=1
OneDayTimeToggle=1
OneDaySlimTimeToggle=1

CurrentTime=12H
OneHourTime=12H
SixHourTime=12H
OneDayTime=12H
OneDaySlimTime=12H

; ====================================================================================================

AQPrimaryColor=FF720080
AQNO2Color=00E838
AQO3Color=00E838
AQSO2Color=00E838
AQPM25Color=FF7200
AQPM10Color=FFFF24
AQCOColor=00E838

AQPrimaryIndex=180
AQNO2Index=60
AQO3Index=60
AQSO2Index=60
AQPM25Index=180
AQPM10Index=120
AQCOIndex=60

; ====================================================================================================

PollenGrassColor1=CECECE
PollenGrassColor2=CECECE
PollenGrassColor3=CECECE
PollenGrassColor4=CECECE
PollenGrassColor5=CECECE
PollenTreeColor1=CECECE
PollenTreeColor2=CECECE
PollenTreeColor3=CECECE
PollenTreeColor4=CECECE
PollenTreeColor5=CECECE
PollenRagweedColor1=CECECE
PollenRagweedColor2=CECECE
PollenRagweedColor3=CECECE
PollenRagweedColor4=CECECE
PollenRagweedColor5=CECECE

; ====================================================================================================

CurrentScale=1
CurrentSlimScale=1
CurrentExtraSlimScale=1
OneHourScale=1
SixHourScale=1
OneDayScale=1
OneDaySlimScale=1
SevenDayScale=1
AirQualityScale=1
PollenScale=1
ScrollMouseIncrement=0.1
