; ============================================================ ;
; CONSTANTS - DO NOT CHANGE
; ============================================================ ;
; These variables are constants and are better untouched!
; Changing anything here will probably break something.
; Only proceed if you know what you do.

[Variables]

LatestVersion=1.1.2
TextUpdate=Update has disabled
ToggleUpdate=Off
DisableUpdate=1
