; ===========================================================================
; 							WEATHER STRING STYLES
; ===========================================================================

[WeatherStyleRetreieve]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontColor=#ColorCode#
FontSize=(30*#WeatherScale#)
AntiAlias=1
DynamicVariables=1

; ===========================================================================
; 							CURRENT STYLES
; ===========================================================================

[WeatherCurrentImageStyle]
ImagePath=#@#Images\Weather
ImageTint=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherCurrentTempStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(62*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherCurrentCondStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(25*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherCurrentFeelsStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(15*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#,128
AntiAlias=1
DynamicVariables=1

[WeatherCurrentFeelsStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(15*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#,128
AntiAlias=1
DynamicVariables=1

[WeatherCurrentValidLocStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(15*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#,128
AntiAlias=1
DynamicVariables=1

[WeatherCurrentTempMaxMinStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(15*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherCurrentSunStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(15*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherCurrentWindStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(15*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherCurrentHumidStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(15*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherCurrentDPStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(15*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherCurrentPressStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(15*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherCurrentUVStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(15*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherCurrentVisStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(15*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherCurrentMPStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(15*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

; ===========================================================================
; 							CURRENT SLIM STYLES
; ===========================================================================

[WeatherCurrentSlimImageStyle]
ImagePath=#@#Images\Weather
ImageTint=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherCurrentSlimTempStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(62*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherCurrentSlimCondStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(25*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherCurrentSlimFeelsStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(15*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#,128
AntiAlias=1
DynamicVariables=1

[WeatherCurrentSlimFeelsStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(15*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#,128
AntiAlias=1
DynamicVariables=1

[WeatherCurrentSlimWindStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(15*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherCurrentSlimHumidStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(15*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherCurrentSlimVisStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(15*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

; ===========================================================================
; 							CURRENT EXTRA SLIM STYLES
; ===========================================================================

[WeatherCurrentExtraSlimImageStyle]
ImagePath=#@#Images\Weather
ImageTint=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherCurrentExtraSlimTempStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(62*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherCurrentExtraSlimCondStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(25*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

; ===========================================================================
; 							ONE HOUR STYLES
; ===========================================================================

[WeatherOneHourImageStyle]
ImagePath=#@#Images\Weather
ImageTint=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneHourValidStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(15*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneHourTempStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(47*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneHourCondStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(25*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneHourFeelsTextStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(10*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneHourFeelsStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(20*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneHourWindTextStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(10*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneHourWindStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(20*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneHourHumidTextStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(10*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneHourHumidStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(20*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneHourUVTextStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(10*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneHourUVStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(20*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

; ===========================================================================
; 							FULL HOUR STYLES
; ===========================================================================

[WeatherFullHourImageStyle]
ImagePath=#@#Images\Weather
ImageTint=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherFullHourTempStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(20*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherFullHourValidStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(10*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherFullHourPrecipStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(15*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherFullHourWindStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(15*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

; ===========================================================================
; 							ONE DAY STYLES
; ===========================================================================

[WeatherOneDayImageStyle]
ImagePath=#@#Images\Weather
ImageTint=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneDayTextStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(15*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneDayTempStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(47*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneDayPrecipStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(20*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneDayWindStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(20*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneDayHumidTextStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(10*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneDayHumidStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(20*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneDayUVTextStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(10*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneDayUVStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(20*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneDaySunMoonTextStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(10*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneDaySunMoonStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(20*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

; ===========================================================================
; 							ONE DAY SLIM STYLES
; ===========================================================================

[WeatherOneDaySlimImageStyle]
ImagePath=#@#Images\Weather
ImageTint=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneDaySlimTextStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(15*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneDaySlimTempStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(47*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneDaySlimPrecipStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(20*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneDaySlimWindStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(20*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneDaySlimHumidTextStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(10*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneDaySlimHumidStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(20*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneDaySlimUVTextStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(10*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneDaySlimUVStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(20*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneDaySlimSunMoonTextStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(10*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherOneDaySlimSunMoonStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(20*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

; ===========================================================================
; 							FORTEEN DAY STYLES
; ===========================================================================

[WeatherForteenDayImageStyle]
ImagePath=#@#Images\Weather
ImageTint=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherForteenDayTempStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(20*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherForteenDayTextStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(10*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherForteenDayPrecipStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(15*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1

[WeatherForteenDayWindStyle]
StringAlign=LeftCenter
FontFace=#TypeFace#
FontSize=(15*#WeatherScale#)
FontWeight=300
FontColor=#ColorCode#
AntiAlias=1
DynamicVariables=1
